/**
 * patch/keyorder-data —— DOM 原型真机 own 键序(authoring 时从 harness/baselines 逐字提取,verbatim)。
 * 与 keyorder.js 的 NAVIGATOR_ORDER 同理:producer 侧静态数据,运行时不读 verifier fixture。
 * 三原型均 per-host:事件处理器密集的 Document/HTMLElement.prototype 真机序随 host 而异(实测 chrome-v143 vs
 * webview-v138 共享键 100+ 处错位);Element.prototype 共享序虽 host 一致,但 host 门控键(ariaNotify webview 无)
 * 致键集不同,故同取 per-host 表 —— 令 reorderOwnKeys 的键集与各 host 注入集精确相等,不触发漂移告警。
 * chrome 序取 linux-chrome-v143、webview 序取 android-webview-v138。Android Chrome 暂无结构 baseline;
 * Document/HTMLElement 的 androidChrome 表由 chrome 表追加已知 mobile touch 键组成,只消除未受控 append
 * 漂移,不声称已证明真机完整顺序。更高版本(v148/v149)基线键集与 v143 漂移,DOM 表仍不按版本扩张。
 */

export const ELEMENT_ORDER = {
  chrome: [
    "namespaceURI", "prefix", "localName", "tagName", "id", "className", "classList", "slot", "attributes",
    "shadowRoot", "part", "assignedSlot", "innerHTML", "outerHTML", "scrollTop", "scrollLeft", "scrollWidth",
    "scrollHeight", "clientTop", "clientLeft", "clientWidth", "clientHeight", "onbeforecopy", "onbeforecut",
    "onbeforepaste", "onsearch", "elementTiming", "onfullscreenchange", "onfullscreenerror",
    "onwebkitfullscreenchange", "onwebkitfullscreenerror", "role", "ariaAtomic", "ariaAutoComplete", "ariaBusy",
    "ariaBrailleLabel", "ariaBrailleRoleDescription", "ariaChecked", "ariaColCount", "ariaColIndex", "ariaColSpan",
    "ariaCurrent", "ariaDescription", "ariaDisabled", "ariaExpanded", "ariaHasPopup", "ariaHidden", "ariaInvalid",
    "ariaKeyShortcuts", "ariaLabel", "ariaLevel", "ariaLive", "ariaModal", "ariaMultiLine", "ariaMultiSelectable",
    "ariaOrientation", "ariaPlaceholder", "ariaPosInSet", "ariaPressed", "ariaReadOnly", "ariaRelevant",
    "ariaRequired", "ariaRoleDescription", "ariaRowCount", "ariaRowIndex", "ariaRowSpan", "ariaSelected",
    "ariaSetSize", "ariaSort", "ariaValueMax", "ariaValueMin", "ariaValueNow", "ariaValueText", "children",
    "firstElementChild", "lastElementChild", "childElementCount", "previousElementSibling", "nextElementSibling",
    "after", "animate", "append", "attachShadow", "before", "checkVisibility", "closest", "computedStyleMap",
    "getAnimations", "getAttribute", "getAttributeNS", "getAttributeNames", "getAttributeNode",
    "getAttributeNodeNS", "getBoundingClientRect", "getClientRects", "getElementsByClassName",
    "getElementsByTagName", "getElementsByTagNameNS", "getHTML", "hasAttribute", "hasAttributeNS", "hasAttributes",
    "hasPointerCapture", "insertAdjacentElement", "insertAdjacentHTML", "insertAdjacentText", "matches",
    "moveBefore", "prepend", "querySelector", "querySelectorAll", "releasePointerCapture", "remove",
    "removeAttribute", "removeAttributeNS", "removeAttributeNode", "replaceChildren", "replaceWith",
    "requestFullscreen", "requestPointerLock", "scroll", "scrollBy", "scrollIntoView", "scrollIntoViewIfNeeded",
    "scrollTo", "setAttribute", "setAttributeNS", "setAttributeNode", "setAttributeNodeNS", "setHTMLUnsafe",
    "setPointerCapture", "toggleAttribute", "webkitMatchesSelector", "webkitRequestFullScreen",
    "webkitRequestFullscreen", "currentCSSZoom", "ariaColIndexText", "ariaRowIndexText",
    "ariaActiveDescendantElement", "ariaControlsElements", "ariaDescribedByElements", "ariaDetailsElements",
    "ariaErrorMessageElements", "ariaFlowToElements", "ariaLabelledByElements", "ariaNotify", "constructor",
  ],
  webview: [
    "namespaceURI", "prefix", "localName", "tagName", "id", "className", "classList", "slot", "attributes",
    "shadowRoot", "part", "assignedSlot", "innerHTML", "outerHTML", "scrollTop", "scrollLeft", "scrollWidth",
    "scrollHeight", "clientTop", "clientLeft", "clientWidth", "clientHeight", "onbeforecopy", "onbeforecut",
    "onbeforepaste", "onsearch", "elementTiming", "onfullscreenchange", "onfullscreenerror",
    "onwebkitfullscreenchange", "onwebkitfullscreenerror", "role", "ariaAtomic", "ariaAutoComplete", "ariaBusy",
    "ariaBrailleLabel", "ariaBrailleRoleDescription", "ariaChecked", "ariaColCount", "ariaColIndex", "ariaColSpan",
    "ariaCurrent", "ariaDescription", "ariaDisabled", "ariaExpanded", "ariaHasPopup", "ariaHidden", "ariaInvalid",
    "ariaKeyShortcuts", "ariaLabel", "ariaLevel", "ariaLive", "ariaModal", "ariaMultiLine", "ariaMultiSelectable",
    "ariaOrientation", "ariaPlaceholder", "ariaPosInSet", "ariaPressed", "ariaReadOnly", "ariaRelevant",
    "ariaRequired", "ariaRoleDescription", "ariaRowCount", "ariaRowIndex", "ariaRowSpan", "ariaSelected",
    "ariaSetSize", "ariaSort", "ariaValueMax", "ariaValueMin", "ariaValueNow", "ariaValueText", "children",
    "firstElementChild", "lastElementChild", "childElementCount", "previousElementSibling", "nextElementSibling",
    "after", "animate", "append", "attachShadow", "before", "checkVisibility", "closest", "computedStyleMap",
    "getAnimations", "getAttribute", "getAttributeNS", "getAttributeNames", "getAttributeNode",
    "getAttributeNodeNS", "getBoundingClientRect", "getClientRects", "getElementsByClassName",
    "getElementsByTagName", "getElementsByTagNameNS", "getHTML", "hasAttribute", "hasAttributeNS", "hasAttributes",
    "hasPointerCapture", "insertAdjacentElement", "insertAdjacentHTML", "insertAdjacentText", "matches",
    "moveBefore", "prepend", "querySelector", "querySelectorAll", "releasePointerCapture", "remove",
    "removeAttribute", "removeAttributeNS", "removeAttributeNode", "replaceChildren", "replaceWith",
    "requestFullscreen", "requestPointerLock", "scroll", "scrollBy", "scrollIntoView", "scrollIntoViewIfNeeded",
    "scrollTo", "setAttribute", "setAttributeNS", "setAttributeNode", "setAttributeNodeNS", "setHTMLUnsafe",
    "setPointerCapture", "toggleAttribute", "webkitMatchesSelector", "webkitRequestFullScreen",
    "webkitRequestFullscreen", "currentCSSZoom", "ariaColIndexText", "ariaRowIndexText",
    "ariaActiveDescendantElement", "ariaControlsElements", "ariaDescribedByElements", "ariaDetailsElements",
    "ariaErrorMessageElements", "ariaFlowToElements", "ariaLabelledByElements", "constructor",
  ],
};

export const DOCUMENT_ORDER = {
  chrome: [
    "implementation", "URL", "documentURI", "compatMode", "characterSet", "charset", "inputEncoding",
    "contentType", "doctype", "documentElement", "xmlEncoding", "xmlVersion", "xmlStandalone", "domain",
    "referrer", "cookie", "lastModified", "readyState", "title", "dir", "body", "head", "images", "embeds",
    "plugins", "links", "forms", "scripts", "currentScript", "defaultView", "designMode", "onreadystatechange",
    "anchors", "applets", "fgColor", "linkColor", "vlinkColor", "alinkColor", "bgColor", "all", "scrollingElement",
    "onpointerlockchange", "onpointerlockerror", "hidden", "visibilityState", "wasDiscarded", "prerendering",
    "featurePolicy", "webkitVisibilityState", "webkitHidden", "onbeforecopy", "onbeforecut", "onbeforepaste",
    "onfreeze", "onprerenderingchange", "onresume", "onsearch", "onvisibilitychange", "timeline",
    "fullscreenEnabled", "fullscreen", "onfullscreenchange", "onfullscreenerror", "webkitIsFullScreen",
    "webkitCurrentFullScreenElement", "webkitFullscreenEnabled", "webkitFullscreenElement",
    "onwebkitfullscreenchange", "onwebkitfullscreenerror", "rootElement", "pictureInPictureEnabled",
    "onbeforexrselect", "onabort", "onbeforeinput", "onbeforematch", "onbeforetoggle", "onblur", "oncancel",
    "oncanplay", "oncanplaythrough", "onchange", "onclick", "onclose", "oncommand",
    "oncontentvisibilityautostatechange", "oncontextlost", "oncontextmenu", "oncontextrestored", "oncuechange",
    "ondblclick", "ondrag", "ondragend", "ondragenter", "ondragleave", "ondragover", "ondragstart", "ondrop",
    "ondurationchange", "onemptied", "onended", "onerror", "onfocus", "onformdata", "oninput", "oninvalid",
    "onkeydown", "onkeypress", "onkeyup", "onload", "onloadeddata", "onloadedmetadata", "onloadstart",
    "onmousedown", "onmouseenter", "onmouseleave", "onmousemove", "onmouseout", "onmouseover", "onmouseup",
    "onmousewheel", "onpause", "onplay", "onplaying", "onprogress", "onratechange", "onreset", "onresize",
    "onscroll", "onscrollend", "onsecuritypolicyviolation", "onseeked", "onseeking", "onselect", "onslotchange",
    "onstalled", "onsubmit", "onsuspend", "ontimeupdate", "ontoggle", "onvolumechange", "onwaiting",
    "onwebkitanimationend", "onwebkitanimationiteration", "onwebkitanimationstart", "onwebkittransitionend",
    "onwheel", "onauxclick", "ongotpointercapture", "onlostpointercapture", "onpointerdown", "onpointermove",
    "onpointerup", "onpointercancel", "onpointerover", "onpointerout", "onpointerenter", "onpointerleave",
    "onselectstart", "onselectionchange", "onanimationend", "onanimationiteration", "onanimationstart",
    "ontransitionrun", "ontransitionstart", "ontransitionend", "ontransitioncancel", "oncopy", "oncut", "onpaste",
    "children", "firstElementChild", "lastElementChild", "childElementCount", "activeElement", "styleSheets",
    "pointerLockElement", "fullscreenElement", "adoptedStyleSheets", "pictureInPictureElement", "fonts",
    "adoptNode", "append", "captureEvents", "caretPositionFromPoint", "caretRangeFromPoint", "clear", "close",
    "createAttribute", "createAttributeNS", "createCDATASection", "createComment", "createDocumentFragment",
    "createElement", "createElementNS", "createEvent", "createExpression", "createNSResolver",
    "createNodeIterator", "createProcessingInstruction", "createRange", "createTextNode", "createTreeWalker",
    "elementFromPoint", "elementsFromPoint", "evaluate", "execCommand", "exitFullscreen", "exitPictureInPicture",
    "exitPointerLock", "getAnimations", "getElementById", "getElementsByClassName", "getElementsByName",
    "getElementsByTagName", "getElementsByTagNameNS", "getSelection", "hasFocus", "hasStorageAccess",
    "hasUnpartitionedCookieAccess", "importNode", "moveBefore", "open", "prepend", "queryCommandEnabled",
    "queryCommandIndeterm", "queryCommandState", "queryCommandSupported", "queryCommandValue", "querySelector",
    "querySelectorAll", "releaseEvents", "replaceChildren", "requestStorageAccess", "requestStorageAccessFor",
    "startViewTransition", "webkitCancelFullScreen", "webkitExitFullscreen", "write", "writeln", "constructor",
    "fragmentDirective", "onpointerrawupdate", "browsingTopics", "hasPrivateToken", "hasRedemptionRecord",
    "activeViewTransition", "onscrollsnapchange", "onscrollsnapchanging", "ariaNotify",
  ],
  webview: [
    "implementation", "URL", "documentURI", "compatMode", "characterSet", "charset", "inputEncoding",
    "contentType", "doctype", "documentElement", "xmlEncoding", "xmlVersion", "xmlStandalone", "domain",
    "referrer", "cookie", "lastModified", "readyState", "title", "dir", "body", "head", "images", "embeds",
    "plugins", "links", "forms", "scripts", "currentScript", "defaultView", "designMode", "onreadystatechange",
    "anchors", "applets", "fgColor", "linkColor", "vlinkColor", "alinkColor", "bgColor", "all", "scrollingElement",
    "onpointerlockchange", "onpointerlockerror", "hidden", "visibilityState", "wasDiscarded", "prerendering",
    "featurePolicy", "webkitVisibilityState", "webkitHidden", "onbeforecopy", "onbeforecut", "onbeforepaste",
    "onfreeze", "onprerenderingchange", "onresume", "onsearch", "onvisibilitychange", "timeline",
    "fullscreenEnabled", "fullscreen", "onfullscreenchange", "onfullscreenerror", "webkitIsFullScreen",
    "webkitCurrentFullScreenElement", "webkitFullscreenEnabled", "webkitFullscreenElement",
    "onwebkitfullscreenchange", "onwebkitfullscreenerror", "rootElement", "pictureInPictureEnabled",
    "onbeforexrselect", "onabort", "onbeforeinput", "onbeforematch", "onbeforetoggle", "onblur", "oncancel",
    "oncanplay", "oncanplaythrough", "onchange", "onclick", "onclose", "oncontentvisibilityautostatechange",
    "oncontextlost", "oncontextmenu", "oncontextrestored", "oncuechange", "ondblclick", "ondrag", "ondragend",
    "ondragenter", "ondragleave", "ondragover", "ondragstart", "ondrop", "ondurationchange", "onemptied",
    "onended", "onerror", "onfocus", "onformdata", "oninput", "oninvalid", "onkeydown", "onkeypress", "onkeyup",
    "onload", "onloadeddata", "onloadedmetadata", "onloadstart", "onmousedown", "onmouseenter", "onmouseleave",
    "onmousemove", "onmouseout", "onmouseover", "onmouseup", "onmousewheel", "onpause", "onplay", "onplaying",
    "onprogress", "onratechange", "onreset", "onresize", "onscroll", "onsecuritypolicyviolation", "onseeked",
    "onseeking", "onselect", "onslotchange", "onstalled", "onsubmit", "onsuspend", "ontimeupdate", "ontoggle",
    "onvolumechange", "onwaiting", "onwebkitanimationend", "onwebkitanimationiteration", "onwebkitanimationstart",
    "onwebkittransitionend", "onwheel", "onauxclick", "ongotpointercapture", "onlostpointercapture",
    "onpointerdown", "onpointermove", "onpointerrawupdate", "onpointerup", "onpointercancel", "onpointerover",
    "onpointerout", "onpointerenter", "onpointerleave", "onselectstart", "onselectionchange", "onanimationend",
    "onanimationiteration", "onanimationstart", "ontransitionrun", "ontransitionstart", "ontransitionend",
    "ontransitioncancel", "oncopy", "oncut", "onpaste", "children", "firstElementChild", "lastElementChild",
    "childElementCount", "activeElement", "styleSheets", "pointerLockElement", "fullscreenElement",
    "adoptedStyleSheets", "pictureInPictureElement", "fonts", "adoptNode", "append", "captureEvents",
    "caretRangeFromPoint", "clear", "close", "createAttribute", "createAttributeNS", "createCDATASection",
    "createComment", "createDocumentFragment", "createElement", "createElementNS", "createEvent",
    "createExpression", "createNSResolver", "createNodeIterator", "createProcessingInstruction", "createRange",
    "createTextNode", "createTreeWalker", "elementFromPoint", "elementsFromPoint", "evaluate", "execCommand",
    "exitFullscreen", "exitPictureInPicture", "exitPointerLock", "getAnimations", "getElementById",
    "getElementsByClassName", "getElementsByName", "getElementsByTagName", "getElementsByTagNameNS",
    "getSelection", "hasFocus", "hasStorageAccess", "hasUnpartitionedCookieAccess", "importNode", "moveBefore",
    "open", "prepend", "queryCommandEnabled", "queryCommandIndeterm", "queryCommandState", "queryCommandSupported",
    "queryCommandValue", "querySelector", "querySelectorAll", "releaseEvents", "replaceChildren",
    "requestStorageAccess", "requestStorageAccessFor", "startViewTransition", "webkitCancelFullScreen",
    "webkitExitFullscreen", "write", "writeln", "oncommand", "onscrollend", "onscrollsnapchange",
    "onscrollsnapchanging", "caretPositionFromPoint", "constructor", "fragmentDirective", "ontouchcancel",
    "ontouchend", "ontouchmove", "ontouchstart",
  ],
};

export const HTML_ELEMENT_ORDER = {
  chrome: [
    "title", "lang", "translate", "dir", "hidden", "inert", "accessKey", "draggable", "spellcheck",
    "autocapitalize", "editContext", "contentEditable", "enterKeyHint", "isContentEditable", "inputMode",
    "virtualKeyboardPolicy", "offsetParent", "offsetTop", "offsetLeft", "offsetWidth", "offsetHeight", "popover",
    "innerText", "outerText", "writingSuggestions", "onbeforexrselect", "onabort", "onbeforeinput",
    "onbeforematch", "onbeforetoggle", "onblur", "oncancel", "oncanplay", "oncanplaythrough", "onchange",
    "onclick", "onclose", "oncommand", "oncontentvisibilityautostatechange", "oncontextlost", "oncontextmenu",
    "oncontextrestored", "oncuechange", "ondblclick", "ondrag", "ondragend", "ondragenter", "ondragleave",
    "ondragover", "ondragstart", "ondrop", "ondurationchange", "onemptied", "onended", "onerror", "onfocus",
    "onformdata", "oninput", "oninvalid", "onkeydown", "onkeypress", "onkeyup", "onload", "onloadeddata",
    "onloadedmetadata", "onloadstart", "onmousedown", "onmouseenter", "onmouseleave", "onmousemove", "onmouseout",
    "onmouseover", "onmouseup", "onmousewheel", "onpause", "onplay", "onplaying", "onprogress", "onratechange",
    "onreset", "onresize", "onscroll", "onscrollend", "onsecuritypolicyviolation", "onseeked", "onseeking",
    "onselect", "onslotchange", "onstalled", "onsubmit", "onsuspend", "ontimeupdate", "ontoggle", "onvolumechange",
    "onwaiting", "onwebkitanimationend", "onwebkitanimationiteration", "onwebkitanimationstart",
    "onwebkittransitionend", "onwheel", "onauxclick", "ongotpointercapture", "onlostpointercapture",
    "onpointerdown", "onpointermove", "onpointerup", "onpointercancel", "onpointerover", "onpointerout",
    "onpointerenter", "onpointerleave", "onselectstart", "onselectionchange", "onanimationend",
    "onanimationiteration", "onanimationstart", "ontransitionrun", "ontransitionstart", "ontransitionend",
    "ontransitioncancel", "oncopy", "oncut", "onpaste", "dataset", "nonce", "autofocus", "tabIndex", "style",
    "attributeStyleMap", "attachInternals", "blur", "click", "focus", "hidePopover", "showPopover",
    "togglePopover", "onscrollsnapchange", "onscrollsnapchanging", "constructor", "onpointerrawupdate",
  ],
  webview: [
    "title", "lang", "translate", "dir", "hidden", "inert", "accessKey", "draggable", "spellcheck",
    "autocapitalize", "editContext", "contentEditable", "enterKeyHint", "isContentEditable", "inputMode",
    "virtualKeyboardPolicy", "offsetParent", "offsetTop", "offsetLeft", "offsetWidth", "offsetHeight", "popover",
    "innerText", "outerText", "writingSuggestions", "onbeforexrselect", "onabort", "onbeforeinput",
    "onbeforematch", "onbeforetoggle", "onblur", "oncancel", "oncanplay", "oncanplaythrough", "onchange",
    "onclick", "onclose", "oncontentvisibilityautostatechange", "oncontextlost", "oncontextmenu",
    "oncontextrestored", "oncuechange", "ondblclick", "ondrag", "ondragend", "ondragenter", "ondragleave",
    "ondragover", "ondragstart", "ondrop", "ondurationchange", "onemptied", "onended", "onerror", "onfocus",
    "onformdata", "oninput", "oninvalid", "onkeydown", "onkeypress", "onkeyup", "onload", "onloadeddata",
    "onloadedmetadata", "onloadstart", "onmousedown", "onmouseenter", "onmouseleave", "onmousemove", "onmouseout",
    "onmouseover", "onmouseup", "onmousewheel", "onpause", "onplay", "onplaying", "onprogress", "onratechange",
    "onreset", "onresize", "onscroll", "onsecuritypolicyviolation", "onseeked", "onseeking", "onselect",
    "onslotchange", "onstalled", "onsubmit", "onsuspend", "ontimeupdate", "ontoggle", "onvolumechange",
    "onwaiting", "onwebkitanimationend", "onwebkitanimationiteration", "onwebkitanimationstart",
    "onwebkittransitionend", "onwheel", "onauxclick", "ongotpointercapture", "onlostpointercapture",
    "onpointerdown", "onpointermove", "onpointerrawupdate", "onpointerup", "onpointercancel", "onpointerover",
    "onpointerout", "onpointerenter", "onpointerleave", "onselectstart", "onselectionchange", "onanimationend",
    "onanimationiteration", "onanimationstart", "ontransitionrun", "ontransitionstart", "ontransitionend",
    "ontransitioncancel", "oncopy", "oncut", "onpaste", "dataset", "nonce", "autofocus", "tabIndex", "style",
    "attributeStyleMap", "attachInternals", "blur", "click", "focus", "hidePopover", "showPopover",
    "togglePopover", "oncommand", "onscrollend", "onscrollsnapchange", "onscrollsnapchanging", "constructor",
    "ontouchcancel", "ontouchend", "ontouchmove", "ontouchstart",
  ],
};

// Android Chrome 是 Chrome host + mobile touch 面。WebView 真机基线确认四键相对序为 cancel/end/move/start;
// 缺 Android Chrome baseline,因此仅把该已知 mobile 尾段叠加到 Chrome host 表,并由代表性 profile 锁稳定性。
const ANDROID_TOUCH_ORDER = ['ontouchcancel', 'ontouchend', 'ontouchmove', 'ontouchstart'];
DOCUMENT_ORDER.androidChrome = [...DOCUMENT_ORDER.chrome, ...ANDROID_TOUCH_ORDER];
HTML_ELEMENT_ORDER.androidChrome = [...HTML_ELEMENT_ORDER.chrome, ...ANDROID_TOUCH_ORDER];
